//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NodePlat.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_NODEPLTYPE                  129
#define IDD_MSG_DLG_FIRST               130
#define IDD_MSG_DLG_SECOND              131
#define IDD_MSG_DLG_THREE               132
#define IDD_PARAM_DLG_FIRST             133
#define IDD_PARAM_DLG_SECOND            134
#define IDD_MSG_DLG_FOURTH              136
#define IDB_MAP                         139
#define IDB_PLANE                       140
#define IDB_MISSILE                     142
#define IDB_SHIP1                       143
#define IDD_MSG_DLG_FIFTH               144
#define IDD_DIALOG1                     144
#define IDR_MENU1                       145
#define IDR_MENU2                       147
#define IDR_SENDREQUEST                 147
#define IDD_MSG_DLG_SIXTH               148
#define IDD_MSG_DLG_SEVENTH             149
#define IDD_MSG_DLG_EIGHTH              150
#define IDD_NETWORKDLG                  151
#define IDD_PARAM_DLG_THIRD             154
#define IDD_PARAM_DLG_FOURTH            155
#define IDD_DB_COM1                     156
#define IDD_DB_ESM1                     157
#define IDD_DB_TRA1                     158
#define IDD_DB_COM                      159
#define IDD_DB_TRA                      161
#define IDD_DB_FUN                      162
#define IDD_DB_SPA                      164
#define IDD_DB_TIM                      166
#define IDD_DB_ESM                      168
#define IDD_DB_PLA                      169
#define IDD_DIALOG_EVALU                170
#define IDD_DIALOG_IdenFus_EVALU        172
#define IDD_DIG_FUSEMULATE_BIAOGE       174
#define IDD_DIG_FUSEMULATE_GRAPH        175
#define IDD_DIALOG_QBSHIBIE             176
#define IDD_DIALOG_ZDSHIBIE             177
#define IDD_DIALOG_QBFUS                178
#define IDD_DIALOG_ZDFUS                179
#define IDD_DIALOG_ZDSHIBIETU           181
#define IDD_DIALOG_QBSHIBIETU           182
#define IDD_DIALOG_QBFUSTU              183
#define IDD_DIALOG_ZDFUSTU              184
#define IDD_DIALOG_QBSINSHIBIE          186
#define IDD_MSG_DLG_NINTH               187
#define IDD_DIALOG_TEN                  188
#define IDD_DIALOG_ELEVENTH             189
#define IDD_DIALOG_TWELFTH              190
#define IDD_DIALOG_THIRTTH              191
#define IDC_LIST_ESM                    1000
#define IDC_LIST_COMMUNICATE            1001
#define IDC_LIST_TRACE                  1002
#define IDC_OURS_TREE                   1003
#define IDC_LIST_FUSIONMSG              1003
#define IDC_LIST_FIRSTIDENTMSG          1003
#define IDC_ENEMY_TREE                  1004
#define IDC_LIST_UNICLUSTERMSG          1004
#define IDC_LIST_MulESM                 1005
#define IDC_LIST_MulTRACE               1007
#define IDC_LIST_MulCOMM                1008
#define IDC_SERVERSET                   1011
#define IDC_TEAMSET                     1012
#define IDC_SERVERIP                    1013
#define IDC_SERIP                       1014
#define IDC_TEAMLIST                    1015
#define IDC_BUTTONCLOSE                 1016
#define IDC_IPADDRESS                   1018
#define IDC_LIST_MSGDISPLAY             1021
#define IDC_DB_TREE                     1022
#define IDC_LIST1                       1023
#define IDC_EDIT_ID                     1024
#define IDC_EDIT_STYLE                  1025
#define IDC_EDIT_DATA1                  1026
#define IDC_BUTMOD                      1027
#define IDC_EDIT1                       1036
#define IDC_COMBO1                      1037
#define IDC_EDIT2                       1037
#define IDC_COMBO2                      1038
#define IDC_COMBO3                      1039
#define IDC_COMBO4                      1040
#define IDC_BUT_ADD                     1041
#define IDC_COMBO5                      1042
#define IDC_BUT_DEL                     1043
#define IDC_COMBO6                      1044
#define IDC_COMBO7                      1045
#define IDC_COMBO8                      1046
#define IDC_COMBO9                      1047
#define IDC_COMBO10                     1048
#define IDC_CHECK1                      1068
#define IDC_CHECK2                      1069
#define IDC_EDIT_PIHAO                  1069
#define IDC_CHECK3                      1070
#define IDC_RADIO_TUXING                1070
#define IDC_CHECK4                      1071
#define IDC_RADIO_BIAOGE                1071
#define IDC_CHECK5                      1072
#define IDC_CHECK6                      1073
#define IDC_COMBO_LEIBIE                1073
#define IDC_CHECK7                      1074
#define IDC_COMBO_FANGSHI               1074
#define IDC_CHECK8                      1075
#define IDC_STATIC1                     1075
#define IDC_CHECK9                      1076
#define IDC_COMBOSORT                   1076
#define IDC_STATIC2                     1076
#define IDC_COMBOTARGETCODE             1077
#define IDC_STATIC3                     1077
#define IDC_RADIO_GRID                  1078
#define IDC_RADIO_GRAPH                 1079
#define IDC_QUEDING                     1080
#define IDC_CANCEAL                     1081
#define IDC_LIST_FUS                    1082
#define IDC_LIST_FUS1                   1083
#define IDC_STATICTU                    1084
#define IDC_LIST_QBSB                   1086
#define IDC_LIST_QBFUS                  1087
#define IDC_LIST_ZDFUS                  1088
#define IDC_LIST_ZDSB                   1091
#define IDC_STATIC_ZDSBTU               1092
#define IDC_LIST_QBSBTU                 1093
#define IDC_LIST_ZDFUSTU                1094
#define IDC_LIST_ZDSBTU                 1095
#define IDC_LIST_QBFUSTU                1096
#define IDC_S2                          1097
#define IDC_S1                          1098
#define IDC_S3                          1099
#define IDC_S4                          1100
#define IDC_S5                          1101
#define IDC_LIST_WUCHA                  1102
#define IDC_BACK                        1103
#define IDC_STATIC01                    1104
#define IDC_STATIC_NB                   1105
#define IDC_STATIC02                    1106
#define IDC_STATIC12                    1107
#define IDC_LIST_SIN                    1108
#define IDC_LIST_EVENT                  1109
#define IDC_LIST_PLAT                   1110
#define IDC_LIST_SPACE                  1111
#define IDC_LIST_FUN                    1112
#define IDC_LIST_INTER                  1113
#define IDM_SYSTEM                      32771
#define IDM_NETWORK_SETTING             32772
#define IDM_TEAM_SERVICE_START          32773
#define IDM_TEAM_SERVICE_STOP           32774
#define IDM_CONNECT_SERVICE             32775
#define IDM_SENDMSG                     32780
#define IDM_DISCONNECT_SERVICE          32782
#define IDM_EVA_SIN                     32784
#define IDM_EVA_MUL                     32785
#define IDM_MATEA                       32786
#define IDM_MATEB                       32787
#define IDM_MATEC                       32788
#define IDM_MATED                       32789
#define IDM_MATEE                       32790
#define IDM_MATEALL                     32791
#define IDM_SENDA                       32793
#define IDM_CLOSEA                      32794
#define IDM_SENDB                       32795
#define IDM_CLOSEB                      32796
#define IDM_SENDD                       32798
#define IDM_CLOSED                      32799
#define IDM_SENDC                       32800
#define IDM_CLOSEC                      32801
#define IDM_SENDE                       32803
#define IDM_CLOSEE                      32804
#define IDM_SENDALL                     32806
#define IDM_CLOSEALL                    32807
#define IDM_EVALUATE                    32813
#define IDM_CLOSE                       32815
#define IDC_MENUITEMA                   32816
#define IDC_MENUITEMB                   32817
#define IDC_MENUITEMC                   32818
#define IDC_MENUITEMD                   32819
#define IDC_MENUITEME                   32820
#define IDC_MENUITEMALL                 32821

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
